### ISSUE TITLE
Broken Whoops library when DeveloperTools module is enabled

### ISSUE THREAD

**Issue by divix1988** [Ppito/laminas-whoops#2]
**Summary**
Can read text when exception is thrown and Whoops library is used on Laminas.

**Current behavior**
![image](https://user-images.githubusercontent.com/6444400/77233849-9cf2ed80-6baa-11ea-9144-aae5044c7c67.png)

**How to reproduce**
include laminas-developer-tools module
include laminas-whoops module
throw any random exception manually
check the Environment and details section

**Expected behavior**
The text should be readable regardless if Laminas contains DeveloperTools module or not.

**Comment by Ppito** [comment]
Hello @divix1988 

I'm very sorry to reply so late, but with the actual pandemic... I totally forgot your issue.
Better late than ever, it's now fixed #5 \o/ 

A custom css resource has been add in the PrettyPageHandler.
Please tell me if you have other display issues.
Until that, the new release version has been published :D 

Have fun :)
