### ISSUE TITLE
When installing via composer; incompatible php version (7.1.7)

### ISSUE THREAD

**Issue by bogal** [Ppito/laminas-whoops#3]
I am getting the following message when adding via composer:

> [InvalidArgumentException]
>   Package ppito/laminas-whoops at version 2.0 has a PHP requirement incompatible with your PHP version (7.1.7)

**Comment by halfpastfouram** [comment]
Minimum required PHP version is 7.2, see [composer.json](https://github.com/Ppito/laminas-whoops/blob/5e6b640ecdd2a6f36cfb9f47ac2bce4e861f692f/composer.json).

**Comment by Ppito** [comment]
PHP 7.1 (and 7.2 now) was no longer supported by php : https://www.php.net/supported-versions.php
If you really want to use an old version, you can use the old version of this package : https://github.com/Ppito/zf3-whoops
